version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./elasticsearch_backups:/usr/share/elasticsearch/backups
    ports:
      - "9200:9200"
    networks:
      - elk

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.8.0
  #   container_name: logstash
  #   volumes:
  #      - ./logstash-pipeline/:/usr/share/logstash/pipeline/
  #     #  - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #   ports:
  #     # - "127.0.0.1:5001:5001/udp"
  #   environment:
  #     # - "PIPELINE_WORKERS=4"
  #     # - "LOG_LEVEL=info"
  #     # - "MONITORING_ENABLED=false"
  #     - "LS_JAVA_OPTS=-Xms256m -Xmx512m"
  #     - "TZ=Europe/Paris"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    # volumes:
      - ./kibana_config.yml:/usr/share/kibana/config/kibana.yml
      # - ./kibana-plugins:/usr/share/kibana/plugins
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
